### ISSUE TITLE
Make the Hash32 and Hash64 overloads which take a byte* public

### ISSUE THREAD

**Issue by NickStrupat** [nickbabcock/Farmhash.Sharp#11]
Hi Nick,

I'm wondering what you think of exposing the unsafe overloads for `Hash32` and `Hash64` methods. I'd rather not create a bunch of `byte[]` when I'm calling it a lot in my already `unsafe` code :)

https://github.com/nickbabcock/Farmhash.Sharp/blob/b49de64485c1963832a56e48a1e6ce9d3f238fd7/Farmhash.Sharp/Farmhash.cs#L123

https://github.com/nickbabcock/Farmhash.Sharp/blob/b49de64485c1963832a56e48a1e6ce9d3f238fd7/Farmhash.Sharp/Farmhash.cs#L527

Thanks,
Nick

**Comment by nickbabcock** [comment]
Makes sense. Feel free to make PR or I can do it. I'll release an update today.

**Comment by NickStrupat** [comment]
https://github.com/nickbabcock/Farmhash.Sharp/pull/12

:)

**Comment by nickbabcock** [comment]
I pushed `0.4` to NuGet. Give it a whirl!
