### ISSUE TITLE
Why uint and not signed int ?

### ISSUE THREAD

**Issue by ciottied** [nickbabcock/Farmhash.Sharp#14]
Great work nick.
I'll will test it for my use case.

Just one curiosity.
Why the 32 bit hash calculation returns a unsigned integer when all the net hash-based collections use 32 bit signed int ?
The fix is easy though.
Best regards.

EC

**Comment by nickbabcock** [comment]
Good question, a couple of reasons:

1. The C++ implementation (and other farmhash implementations) use unsigned 32 and 64bit integers
1. I believe most other languages use unsigned integers when hashing in general (Java is an exception as it doesn't have unsigned integers and I believe C# took inspiration from this). Go and Rust use unsigned integers for their hash interfaces.
1. If `Hash32` starts to return `int` should `Hash64` return `long`? 
1. When using Farmhash.Sharp, one should almost always use the 64bit hash as it is 2x-3x faster than the 32bit hash, so this might mean that `Hash64` should return an `int` as it should be the go to.

To me the best solution would be to create new type of C# dictionary that works with 64bit hashes (something that I have been kicking around in my head) 😄 

But if you want to work use dictionaries then my recommendation is to use `Hash64` and truncate to `int` (or XOR with itself shifted 32bits)

**Comment by nickbabcock** [comment]
I'm closing this issue as I think your original question is answered (if not, let me know and we can continue the discussion)

**Comment by ciottied** [comment]
Thanks
